//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitHoursApp.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BitHoursApp.Common.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string Common_Email {
            get {
                return ResourceManager.GetString("Common_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CapsLock is enabled.
        /// </summary>
        internal static string Common_LoginDialog_CapsLockOn {
            get {
                return ResourceManager.GetString("Common_LoginDialog_CapsLockOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo:.
        /// </summary>
        internal static string Common_Memo {
            get {
                return ResourceManager.GetString("Common_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Common_Menu_Exit {
            get {
                return ResourceManager.GetString("Common_Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        internal static string Common_Menu_File {
            get {
                return ResourceManager.GetString("Common_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Common_Menu_Logout {
            get {
                return ResourceManager.GetString("Common_Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh tracking room.
        /// </summary>
        internal static string Common_Menu_RefreshRoom {
            get {
                return ResourceManager.GetString("Common_Menu_RefreshRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        internal static string Common_Menu_View {
            get {
                return ResourceManager.GetString("Common_Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Common_Password {
            get {
                return ResourceManager.GetString("Common_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string Common_SignIn {
            get {
                return ResourceManager.GetString("Common_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start tracking time.
        /// </summary>
        internal static string Common_StartTrackingTime {
            get {
                return ResourceManager.GetString("Common_StartTrackingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop tracking time.
        /// </summary>
        internal static string Common_StopTrackingTime {
            get {
                return ResourceManager.GetString("Common_StopTrackingTime", resourceCulture);
            }
        }
    }
}
